REF_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/splicemutr_references"
GTF_URL : "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
GTF_FILE_GZ : "gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
FASTA_URL : "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/GRCh38.primary_assembly.genome.fa.gz"
FASTA_FILE_GZ : "GRCh38.primary_assembly.genome.fa.gz"

GTF_FILE : "gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
SPLICEMUTR_SCRIPTS : "/users/tpalmer/splicemute/scripts"
OUT_FILE : "G026_txdb.sqlite"

LEAF_DIR : "/users/tpalmer/leafcutter"
GTF : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/splicemutr_references/gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
ANN_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/splicemutr_references/annotations"

FASTA_FILE : "GRCh38.primary_assembly.genome.fa"
TWOBIT_FILE : "GRCh38.primary_assembly.genome.2bit"
FA_TO_TWOBIT_EXEC : "/users/tpalmer/packages/ucsc/faToTwoBit"

SEED_FILE : "/users/tpalmer/splicemutr_snakemake_example/prep_ref/DESCRIPTION"
BSGENOME : "BSgenome.Hsapiens.GENCODE.GRCh38.p10"

TCGA_CANCER : "CHOL"
JUNC_OUTPUT_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/juncs"
SAMPLES : "all"

STAR_FILES : "/dcs04/fertig/data/theron/share/bams/SJ_OUT/SJ_files.txt"
LEAFCUTTER_OUTPUT_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/leafcutter_output"
FILTERED_STAR_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/leafcutter_output/filtered_star_files"
SPLICEMUTR_FUNCTIONS : "/users/tpalmer/splicemute/R/functions.R"
JUNC_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/juncs"
JUNCFILE_FILENAMES : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/juncs/filenames.txt"
LEAFCUTTER_SCRIPTS : "/users/tpalmer/packages/leafcutter/scripts"
LEAFVIZ_DIR : "/users/tpalmer/packages/leafcutter/leafviz"
GROUPS_FILE : "/dcs04/fertig/data/theron/splicemutr_paper/CHOL_groups_file.txt"
LEAFCUTTER_PYTHON : "/users/tpalmer/packages/leafcutter/clustering"

FORMED_TRANSCRIPTS_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/formed_transcripts"
INTRON_FILE : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/juncs/CHOL_introns.rds"
TXDB : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/splicemutr_references/G026_txdb.sqlite"
SPLICEMUTR_FUNCTIONS : "/users/tpalmer/splicemute/R/functions.R"

SPLICEMUTR_FILES : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/formed_transcripts/filenames_cp.txt"
COMBINE_SPLICEMUTR_OUT : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/combine_splicemutr_out"

PROTEINS : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/combine_splicemutr_out/proteins.txt"
PROCESS_PEPTIDES_OUT : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/process_peptides_out"
SPLICEMUTR_PYTHON : "/users/tpalmer/splicemute/inst"

GENOTYPES_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/genotypes"
BAMFILES : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/bamfiles/bamfiles.txt"

TYPE : "I"
INPUT_KMERS : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/process_peptides_out/peps_9.txt"
MHC_ALLELE_FILE : "/dcs04/fertig/data/theron/splicemutr_TCGA/CHOL/CHOL_class1_alleles.txt"
MHCNUGGETS_OUT : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/mhcnuggets_out"

NUM_ALLELE_FILES : 63
KMER_LENGTH : 9
PROCESS_BINDAFF_OUT : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/process_bindaff_out"
PICKLE_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/process_peptides_out"
KMER_SIZE_MIN : 9
KMER_SIZE_MAX : 10

SPLICE_DAT_FILE : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/combine_splicemutr_out/data_splicemutr_all_pep.txt"
SUMMARY_TYPE : "IC50"
ANALYZE_SPLICEMUTR_OUT : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/analyze_splicemutr_out"
GENOTYPES_REFORMATTED : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/CHOL_genotypes_specfic.txt"
SUMMARY_DIR : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/process_bindaff_out"

KMER_COUNTS_FILES : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/analyze_splicemutr_out/filenames.txt"
KMER_COUNTS_OUT : "/dcs04/fertig/data/theron/splicemutr_snakemake_example/kmer_counts_out"