get_reference_data:
    REF_DIR : "splicemutr_references"
    GTF_URL : "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
    GTF_FILE_GZ : "gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
    FASTA_URL : "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_26/GRCh38.primary_assembly.genome.fa.gz"
    FASTA_FILE_GZ : "GRCh38.primary_assembly.genome.fa.gz"
    
make_txdb:
    REF_DIR : "splicemutr_references"
    GTF_FILE : "gencode.v26.chr_patch_hapl_scaff.annotation.gtf"
    SPLICEMUTR_SCRIPTS : "/splicemute/scripts"
    OUT_FILE : "G026_txdb.sqlite"
    
prepare_leafcutter_references:
    LEAF_DIR : "leafcutter"
    GTF : "splicemutr_references/gencode.v26.chr_patch_hapl_scaff.annotation.gtf.gz"
    ANN_DIR : "splicemutr_references/annotations"
    
convert_fasta_twobit:
    REF_DIR : "splicemutr_references"
    FASTA_FILE : "GRCh38.primary_assembly.genome.fa"
    TWOBIT_FILE : "GRCh38.primary_assembly.genome.2bit"
    FA_TO_TWOBIT_EXEC : "faToTwoBit"
    
create_bsgenome:
    REF_DIR : "splicemutr_references"
    SEED_FILE : "DESCRIPTION"
    SPLICEMUTR_SCRIPTS : "/splicemute/scripts"
    BSGENOME : "BSgenome.Hsapiens.GENCODE.GRCh38.p26"
