SPLICEMUTR_PYTHON : "splicemutr/python_scripts"
SPLICEMUTR_SCRIPTS : "splicemutr/Rscripts"
SIMULATED_READS : "simulated_reads"
SPLICEMUTR : "splicemutr"
NUM_SAMPLES : 8
SPLICEMUTR_FUNCTIONS : "splicemutr/Rfunctions/functions.R"
LEAFCUTTER_SCRIPTS : "leafcutter/scripts"
REF_DIR : "splicemutr_references/annotations"
LEAFVIZ_DIR : "leafcutter/leafviz"
LEAFCUTTER_PYTHON : "splicemutr/python_scripts"

